version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - Postgres_data:/var/lib/Postgres
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DATABASE: "db"
    ports:
      - "8000:5432" 

  manager:
    depends_on:
     - postgres
    build:
      context: "./manager"
      dockerfile: "Dockerfile"
    image: test3011
    environment:
      CSV_FILENAME: "data.csv"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DATABASE: "db"
    links:
       - "postgres:db"
    
volumes:
  Postgres_data: {}